### ISSUE TITLE
Experimental Configurations

### ISSUE THREAD

**Issue by RobertVillalba** [VerifiableRobotics/LTLMoP#59] opened 2014-03-13 17:20 UTC
Added Experimental Configurations disappear after hitting apply. (Windows)

**Comment by jimjing** [comment] 2014-03-13 19:01
can you give me some more info to reproduce this? thanks J

**Comment by RobertVillalba** [comment] 2014-03-14 04:35
Hmm it seems like perhaps it wasn't an issue, maybe just not intuitive. Essentially if you click new and do things like setting up its name it will not be there once you click ok and open up the configuration again. However it does seem to remain if I add a robot. Perhaps that was a design choice.

**Comment by jimjing** [comment] 2014-03-14 15:00
If you have a look at the logging message in console there should be something like Can't find robot in the config. Abort saving. The reason is that if there is no robot in the current config, LTLMoP won't be able to run the execution later. I am working on an updated version of the config editor which will give more clear information to user when no robot is given.

**Comment by jimjing** [comment] 2014-04-18 03:43
i think this is fixed. let me know if you still run into this. otherwise please close this issue

**Closed as completed** 2014-04-18 16:27 UTC
