### ISSUE TITLE
You can type on SimGUI log

### ISSUE THREAD

**Issue by wongkaiweng** [VerifiableRobotics/LTLMoP#37] opened 2013-05-16 19:33 UTC
SimGUI log ca be edited by user. You can move the cursors and the printing to the log will be messed up.

**Comment by cfinucane** [comment] 2013-05-17 20:56
The cursor-moving problem is fixed with a1c432c57d8e0964.  However, I can't reproduce the bug where you say the log text is editable on OS X or Ubuntu.  Can you provide more detail?

**Comment by wongkaiweng** [comment] 2013-06-20 05:24
I think the problem is fixed with a1c432c57d8e0964. I cannot reproduce it on the development branch. The following happens only on my slugs branch.

---

![image](https://f.cloud.github.com/assets/734271/679458/4154233e-d969-11e2-82a5-1a9c5f25fa64.png)

This is the original simulation GUI window. Now I will edit the blue line. I can replace the blue line with "LTLMOP"s.

![image](https://f.cloud.github.com/assets/734271/679459/7e8d9f0a-d969-11e2-9ac8-416dcd39ec9f.png)

**Comment by cfinucane** [comment] 2013-06-20 14:50
Great, thanks; closing.

**Closed as completed by cfinucane** 2013-06-20 14:50 UTC
Labels: cosmetic
